### ISSUE TITLE
WindowsError [Error 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by andyetzel** [andyetzel/forcepoint_support_assist#12]
* Forcepoint Support Assist version: v0.6.0
* Python version: Python 2.x, Python 3.x
* Operating System: Windows

### Description

Tried to run v0.6.0 script on non-FSM server.
The following errors are presented to the terminal as the EIP registry keys are not present (expected behavior).  This causes several Global Constants to be improperly assigned, affecting other areas of the script.

The script does continue to collect the remaining DLP and Windows data as expected, but fails to ZIP the logs and copy to the desktop.  This is likely due to the script exiting prematurely.

These errors should be cleaned up for better presentation to the console, but should include this detail for the log file.

### What I Did
1) Run forcepoint_support_assist.py on secondary DLP server
2) Encounter the following errors:
![image](https://user-images.githubusercontent.com/25411475/71270777-4524bc00-2307-11ea-8941-7c1615de14ba.png)

```
C:\Users\administrator.TSLAB\Desktop>python forcepoint_support_assist.py
ERROR:root:Not a Forcepoint Security Management Server
Traceback (most recent call last):
  File "forcepoint_support_assist.py", line 90, in get_eip_path
    hKey = _winreg.OpenKey(_winreg.HKEY_LOCAL_MACHINE, 'Software\\Wow6432Node\\W
ebsense\\EIP Infra')
WindowsError: [Error 2] The system cannot find the file specified

ERROR:root:Critical error has been encountered.
Traceback (most recent call last):
  File "forcepoint_support_assist.py", line 106, in get_eip_version
    if os.path.exists(EIP_XML):
NameError: global name 'EIP_XML' is not defined
Critical error has been encountered.
Traceback (most recent call last):
  File "forcepoint_support_assist.py", line 106, in get_eip_version
    if os.path.exists(EIP_XML):
NameError: global name 'EIP_XML' is not defined
ERROR:root:A critical error has occurred.
Traceback (most recent call last):
  File "forcepoint_support_assist.py", line 173, in get_sql_settings
    if os.path.exists(EIP_XML):
NameError: global name 'EIP_XML' is not defined
A critical error has occurred.
Traceback (most recent call last):
  File "forcepoint_support_assist.py", line 173, in get_sql_settings
    if os.path.exists(EIP_XML):
NameError: global name 'EIP_XML' is not defined

WARNING:root:Not a Forcepoint Security Manager.
Not a Forcepoint Security Manager.

C:\Users\administrator.TSLAB\Desktop>
```

**Comment by andyetzel** [comment]
Should, consider skipping execution of FSM related logic when running on Secondary DLP server.  Perhaps include all FSM logic within a new class?
